### Registering user

POST http://localhost:3000/api/v1/users/register

{
    "firstName": "jono",
    "lastName": "doe",
    "username": "jonodoe",
    "email": "jono@test.com",
    "password": "123456"
}

### Login user

POST http://localhost:3000/api/v1/users/login

{
    "email": "jono@test.com",
    "password": "123456"
}

### Get Tasks

GET http://localhost:3000/api/v1/tasks

### Create Task

POST http://localhost:3000/api/v1/tasks

{
    "name": "nurul task 5",
    "description": "description task nya nurul 5",
    "isCompleted": true,
    "userId": "1"
}